version: '2'
services:
    bankmellat-app:
        image: bankmellat
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bankmellat-postgresql:5432/bankmellat
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bankmellat-postgresql:
        extends:
            file: postgresql.yml
            service: bankmellat-postgresql
